### ISSUE TITLE
Two newbie usage issues

### ISSUE THREAD

**Issue by suntong** [OriAmir/React-Responsive-Gallery#47]
First of all, I've exhausted all possible (react based) image galleries, and this is by far the most simplest to use. Even for people without any node/react/js background can use it. Thanks a lot for providing such out-of-box support!

Now, here are two newbie usage issues I encountered.

- First, currently I'm starting my site with `npx vite`, is there any other ways to start it please?
- The reason I ask above is, https://github.com/vitejs/vite/issues/15287, i.e., I cannot make it go background. 
I.e., I'm starting the site from my remote server, but I'm unable to quit my ssh session, else the site will die.

**Comment by OriAmir** [comment]
Hello @suntong , thanks for the words, really appreciate it.

Looks like your 2 questions are more general questions  and not specific to the library

1. first you need to understand what is `npx`- `NPX` stands for Node Package eXecute. It is simply an NPM package runner. It allows developers to execute any Javascript Package available on the NPM registry without even installing it. so acstully you can just go into the folder where your project is and then run a script from the `package.json` such `npm run dev`.
2. not sure about that since I never try viteJs in remote server but probably better to see if there is anything in their docs - https://vitejs.dev/guide/

**Comment by suntong** [comment]
Yes, indeed, they're newbie questions, thanks a lot for answering them.

**Comment by OriAmir** [comment]
sure.
@suntong if you like the library pls STAR it, it's will help, thanks.

**Comment by suntong** [comment]
Already STARed it. Well deserved! Thanks!
